package com.hyh.api.entity;

/**
 * 插件生成的实体类
 * @author hyhsoftware@163.com
 * @version 0.0.2
 */
public class ActionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.id
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.name
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.action_code
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    private String actionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.id
     *
     * @return the value of action_log.id
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.id
     *
     * @param id the value for action_log.id
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.name
     *
     * @return the value of action_log.name
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.name
     *
     * @param name the value for action_log.name
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.action_code
     *
     * @return the value of action_log.action_code
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.action_code
     *
     * @param actionCode the value for action_log.action_code
     *
     * @mbggenerated Mon Aug 28 11:10:37 CST 2017
     */
    public void setActionCode(String actionCode) {
        this.actionCode = actionCode == null ? null : actionCode.trim();
    }
}